In [1]:
import pandas as pd;import numpy as np;import matplotlib.pyplot as plt; import seaborn as sns 

In [2]:
df=pd.read_csv(r"C:\Data science\Machine learning with phyton\data set\NLP\Tweets.csv")

In [3]:
type(df)

pandas.core.frame.DataFrame

In [4]:
df.shape

(14640, 15)

In [5]:
df.head()

tweet_id airline_sentiment  airline_sentiment_confidence  \
0  570306133677760513           neutral                        1.0000   
1  570301130888122368          positive                        0.3486   
2  570301083672813571           neutral                        0.6837   
3  570301031407624196          negative                        1.0000   
4  570300817074462722          negative                        1.0000   

  negativereason  negativereason_confidence         airline  \
0            NaN                        NaN  Virgin America   
1            NaN                     0.0000  Virgin America   
2            NaN                        NaN  Virgin America   
3     Bad Flight                     0.7033  Virgin America   
4     Can't Tell                     1.0000  Virgin America   

  airline_sentiment_gold        name negativereason_gold  retweet_count  \
0                    NaN     cairdin                 NaN              0   
1                    NaN    jnardino                 NaN              0   
2                    NaN  yvonnalynn                 NaN              0   
3                    NaN    jnardino                 NaN              0   
4                    NaN    jnardino                 NaN              0   

                                                text tweet_coord  \
0                @VirginAmerica What @dhepburn said.         NaN   
1  @VirginAmerica plus you've added commercials t...         NaN   
2  @VirginAmerica I didn't today... Must mean I n...         NaN   
3  @VirginAmerica it's really aggressive to blast...         NaN   
4  @VirginAmerica and it's a really big bad thing...         NaN   

               tweet_created tweet_location               user_timezone  
0  2015-02-24 11:35:52 -0800            NaN  Eastern Time (US & Canada)  
1  2015-02-24 11:15:59 -0800            NaN  Pacific Time (US & Canada)  
2  2015-02-24 11:15:48 -0800      Lets Play  Central Time (US & Canada)  
3  2015-02-24 11:15:36 -0800            NaN  Pacific Time (US & Canada)  
4  2015-02-24 11:14:45 -0800            NaN  Pacific Time (US & Canada)

In [6]:
x=df.iloc[:,10]
y=df.iloc[:,1]

In [7]:
import re 
print(x.head())


0                  @VirginAmerica What @dhepburn said.
1    @VirginAmerica plus you've added commercials t...
2    @VirginAmerica I didn't today... Must mean I n...
3    @VirginAmerica it's really aggressive to blast...
4    @VirginAmerica and it's a really big bad thing...
Name: text, dtype: object


In [8]:
text=[]
for i in range(0,len(x)):
    clean_text=re.sub(r'\W',' ',str(x[i]))
    clean_text=re.sub(r'\s+[a-zA-Z]\s+',' ',clean_text)
    clean_text=re.sub(r'\^[a-zA-Z]\s+',' ',clean_text)
    clean_text=re.sub(r'\s+',' ',clean_text)
    clean_text=clean_text.lower()
    text.append(clean_text)

In [9]:
text

[' virginamerica what dhepburn said ',
 ' virginamerica plus you ve added commercials to the experience tacky ',
 ' virginamerica didn today must mean need to take another trip ',
 ' virginamerica it really aggressive to blast obnoxious entertainment in your guests faces amp they have little recourse',
 ' virginamerica and it a really big bad thing about it',
 ' virginamerica seriously would pay 30 flight for seats that didn have this playing it really the only bad thing about flying va',
 ' virginamerica yes nearly every time fly vx this ear worm won go away ',
 ' virginamerica really missed prime opportunity for men without hats parody there https co mwpg7grezp',
 ' virginamerica well didn but now do d',
 ' virginamerica it was amazing and arrived an hour early you re too good to me ',
 ' virginamerica did you know that suicide is the second leading cause of death among teens 10 24',
 ' virginamerica lt 3 pretty graphics so much better than minimal iconography d',
 ' virginamerica th

In [10]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Anuja\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [11]:

from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

In [12]:
newdata=TfidfVectorizer(max_features=2000,stop_words=stopwords.words('english'))

In [13]:
newx=newdata.fit_transform(text).toarray()

In [14]:
newx.shape

(14640, 2000)

In [15]:
from sklearn.preprocessing import  LabelEncoder
l1=LabelEncoder()
y=l1.fit_transform(y)

In [16]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(newx,y,train_size=0.8)

In [17]:
from sklearn.neural_network import MLPClassifier
algo=MLPClassifier()
algo.fit(xtrain,ytrain)

C:\Users\Anuja\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100,), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score
ypre=algo.predict(xtest)

In [19]:
print(confusion_matrix(ytest,ypre))
print(accuracy_score(ytest,ypre))

[[1499  238  107]
 [ 194  334   80]
 [  72   95  309]]
0.7315573770491803


In [20]:
from sklearn.ensemble import RandomForestClassifier
algo2=RandomForestClassifier(n_estimators=10)
algo2.fit(xtrain,ytrain)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [21]:
ypred=algo2.predict(xtest)

In [22]:
confusion_matrix(ytest,ypred)

array([[1680,  121,   43],
       [ 354,  216,   38],
       [ 167,   67,  242]], dtype=int64)

In [23]:
accuracy_score(ytest,ypred)

0.730191256830601